"""Bounded, machine-generated README status block writer (Issue #54).

Writes only the byte range between two HTML-comment markers already present in
``README.md``; every other byte of the file -- all Human-authored prose, including the
existing ``## Status`` section this block sits beside -- is preserved exactly.
``docs/project_sources/00_SOURCE_AUTHORITY_INDEX.md`` section 13 fixes README as a
lower-authority, non-canonical source; this script never decides Phase completion,
acceptance, or Roadmap meaning, it only echoes fields ``03_CURRENT_DEVELOPMENT_STATE.md``
already records.

Refuses (``SystemExit``) rather than silently appending when the two markers are
missing, duplicated, or out of order -- an unbounded write is not a smaller version of a
bounded one. Never touches any file under ``docs/project_sources/``.
"""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts.bounded_generated_block import apply_bounded_block
    from scripts.validate_source_freshness import extract_fields
except ImportError:  # running as `python scripts/generate_readme_status_block.py` directly
    from bounded_generated_block import (  # type: ignore[import-not-found,no-redef]
        apply_bounded_block,
    )
    from validate_source_freshness import extract_fields  # type: ignore[import-not-found,no-redef]

BEGIN_MARKER = "<!-- SOURCE_STATUS:GENERATED:BEGIN -->"
END_MARKER = "<!-- SOURCE_STATUS:GENERATED:END -->"

#: The subset of 03_CURRENT_DEVELOPMENT_STATE.md's own fields this bounded block echoes,
#: in display order. Deliberately small: the block is a pointer to the canonical source,
#: not a duplicate of it -- see docs/project_sources/00_SOURCE_AUTHORITY_INDEX.md section
#: 10, "two differently...formatted files containing substantially the same [content]
#: must not both be presented as current canonical sources".
_ECHOED_FIELDS: tuple[str, ...] = (
    "OBSERVED_AT_UTC",
    "COMPLETED_THROUGH_PHASE",
    "CURRENT_PHASE",
    "CURRENT_PHASE_STATE",
    "PHASE_13_COMPLETE",
    "PHASE_14_ALLOWED",
)


def render_block(recorded: dict[str, str]) -> str:
    lines = [
        BEGIN_MARKER,
        "<!-- generated by scripts/generate_readme_status_block.py -- do not edit by hand -->",
        "",
        "### Source status (generated)",
        "",
        "This block is machine-generated from "
        "[`docs/project_sources/03_CURRENT_DEVELOPMENT_STATE.md`](docs/project_sources/"
        "03_CURRENT_DEVELOPMENT_STATE.md) and is not Human-authored explanatory text. It "
        "is a dated projection, not a perpetual truth source -- see "
        "[`docs/project_sources/00_SOURCE_AUTHORITY_INDEX.md`]"
        "(docs/project_sources/00_SOURCE_AUTHORITY_INDEX.md).",
        "",
        "```text",
    ]
    for key in _ECHOED_FIELDS:
        if key in recorded:
            lines.append(f"{key}={recorded[key]}")
    lines.append("GENERATED_FROM=docs/project_sources/03_CURRENT_DEVELOPMENT_STATE.md")
    lines.append("THIS_BLOCK_IS_MACHINE_GENERATED=true")
    lines.append("```")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def apply(readme_text: str, block: str) -> str:
    """Delegates to :func:`scripts.bounded_generated_block.apply_bounded_block` (Issue #57)
    -- this function's own name and signature are kept for every existing caller, but the
    replacement algorithm itself now has exactly one implementation, shared with
    ``merge_source_reflow.py``'s ``HANDOFF.md`` writer."""

    return apply_bounded_block(readme_text, block, BEGIN_MARKER, END_MARKER)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("docs/project_sources/03_CURRENT_DEVELOPMENT_STATE.md"),
        help="the document this block's fields are echoed from",
    )
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if applying the generator would change README.md, without "
        "writing anything (for CI use)",
    )
    args = parser.parse_args(argv)

    recorded = extract_fields(args.source.read_text(encoding="utf-8"))
    block = render_block(recorded)
    original = args.readme.read_text(encoding="utf-8")
    updated = apply(original, block)

    if args.check:
        return 0 if updated == original else 1

    if updated != original:
        args.readme.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
