"""Post-merge deterministic reflow (Issue #57,
`03_BINDING/MERGE_SOURCE_REFLOW_CONTRACT.md` sections 3-9).

Regenerates exactly the closed set of machine-owned surfaces
:data:`ALLOWLISTED_GENERATED_PATHS` names, from the exact accepted `main` SHA and the
repository's own already-Human-authored sources -- never from its own prior output, never by
inventing semantic content those sources do not already record.

Two layers, matching this repository's own established split (`collect_repository_snapshot`
vs `validate_source_freshness`, `evaluate_adoption_record`'s pure evaluation vs the GitHub
Adapter it deliberately never becomes): :func:`compute_outputs` is a pure function of its
inputs -- no filesystem read beyond what the caller already supplied, no filesystem write, no
git subprocess -- and :func:`apply_reflow` is the one place that reads the current on-disk
state of the allowlisted paths, diffs against the freshly computed bytes, and writes only
what changed, atomically, only after every output has been computed successfully.
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping
from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any

try:
    from scripts.bounded_generated_block import apply_bounded_block, human_text_outside_block
    from scripts.generate_readme_status_block import (
        BEGIN_MARKER as README_BEGIN_MARKER,
        END_MARKER as README_END_MARKER,
        render_block as render_readme_block,
    )
    from scripts.validate_source_freshness import extract_fields
except ImportError:  # running as `python scripts/merge_source_reflow.py` directly
    from bounded_generated_block import (  # type: ignore[import-not-found,no-redef]
        apply_bounded_block,
        human_text_outside_block,
    )
    from generate_readme_status_block import (  # type: ignore[import-not-found,no-redef]
        BEGIN_MARKER as README_BEGIN_MARKER,
        END_MARKER as README_END_MARKER,
        render_block as render_readme_block,
    )
    from validate_source_freshness import extract_fields  # type: ignore[import-not-found,no-redef]

SCHEMA_VERSION = "0.1"

HANDOFF_BEGIN_MARKER = "<!-- HANDOFF_STATUS:GENERATED:BEGIN -->"
HANDOFF_END_MARKER = "<!-- HANDOFF_STATUS:GENERATED:END -->"

#: The content a brand-new `HANDOFF.md` starts from -- exactly one well-formed marker pair,
#: so the very first reflow can use the identical `apply_bounded_block` path a later
#: regeneration does, rather than a special-cased "file did not exist yet" branch.
INITIAL_HANDOFF_SKELETON = (
    "# Handoff\n\n"
    "<!-- Human semantic handoff decisions belong above this line, outside the generated "
    "block below. -->\n\n"
    f"{HANDOFF_BEGIN_MARKER}\n{HANDOFF_END_MARKER}\n"
)

RECEIPT_PATH = "docs/project_sources/generated/SOURCE_REFLOW_RECEIPT.json"

#: The closed set of paths `apply_reflow` may ever write (contract section 4). Any output
#: `compute_outputs` produces outside this set is a defect in this module, caught by the
#: assertion in `compute_outputs` itself and proven absent by
#: `test_every_computed_output_path_is_allowlisted`.
ALLOWLISTED_GENERATED_PATHS: frozenset[str] = frozenset(
    {
        "docs/project_sources/generated/CURRENT_REPOSITORY_FACTS.json",
        "docs/project_sources/generated/REPOSITORY_TREE.txt",
        "docs/project_sources/generated/PHASE_EVIDENCE_INDEX.json",
        RECEIPT_PATH,
        "HANDOFF.md",
        "SHA256SUMS",
        "README.md",
    }
)


def _looks_like_git_sha(value: str) -> bool:
    return len(value) in (40, 64) and all(c in "0123456789abcdefABCDEF" for c in value)


def verify_head_matches(main_sha: str, actual_head_sha: str) -> None:
    """Refuse (``SystemExit``) when the caller's claimed ``main_sha`` disagrees with the
    real, independently resolved checkout HEAD -- the stale-SHA guard (contract section 9).
    """

    if main_sha != actual_head_sha:
        raise SystemExit(
            f"stale main_sha: caller claims {main_sha!r} but the checked-out HEAD is "
            f"{actual_head_sha!r}"
        )


def render_handoff_block(
    main_sha: str, observed_at_utc: str, recorded_state: Mapping[str, str]
) -> str:
    lines = [
        HANDOFF_BEGIN_MARKER,
        "<!-- generated by scripts/merge_source_reflow.py -- do not edit by hand -->",
        "",
        "### Handoff status (generated)",
        "",
        "```text",
        f"MAIN_SHA={main_sha}",
        f"OBSERVED_AT_UTC={observed_at_utc}",
    ]
    for key in ("COMPLETED_THROUGH_PHASE", "CURRENT_PHASE", "CURRENT_PHASE_STATE"):
        if key in recorded_state:
            lines.append(f"{key}={recorded_state[key]}")
    lines.append("TRANSFER_STATUS=NOT_DECLARED")
    lines.append("THIS_BLOCK_IS_MACHINE_GENERATED=true")
    lines.append("```")
    lines.append("")
    lines.append(HANDOFF_END_MARKER)
    return "\n".join(lines)


def compute_sha256sums(files: Mapping[str, bytes]) -> str:
    """A deterministic ``<sha256>  <path>`` manifest, sorted by path.

    Raises ``ValueError`` if *files* itself carries a ``SHA256SUMS`` entry -- the manifest
    must never hash itself (contract section 5).
    """

    if "SHA256SUMS" in files:
        raise ValueError("SHA256SUMS must not include itself in its own manifest")
    lines = [f"{hashlib.sha256(files[path]).hexdigest()}  {path}" for path in sorted(files)]
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class ReflowInputs:
    """Every fact :func:`compute_outputs` reads. No field here is itself a prior output of
    this module -- see the idempotence argument in the contract document section 7."""

    main_sha: str
    observed_at_utc: str
    current_development_state_text: str
    phase_ledger_text: str
    tracked_paths: tuple[str, ...]
    readme_text: str
    handoff_text: str | None
    source_document_texts: Mapping[str, str] = field(default_factory=dict)


def compute_outputs(inputs: ReflowInputs) -> dict[str, bytes]:
    """Return every allowlisted path's full new content, computed purely from *inputs* --
    except :data:`RECEIPT_PATH`, whose ``files_written``/``files_unchanged`` fields can only
    be known once the caller has compared against the current on-disk state (see
    :func:`apply_reflow`).

    Raises ``SystemExit`` -- before writing anything, since this function performs no I/O at
    all -- for a malformed ``main_sha`` or a ``HANDOFF.md``/``README.md`` whose Human text
    would change across the regeneration.
    """

    if not _looks_like_git_sha(inputs.main_sha):
        raise SystemExit(f"main_sha does not look like a git commit SHA: {inputs.main_sha!r}")

    recorded_state = extract_fields(inputs.current_development_state_text)
    recorded_ledger = extract_fields(inputs.phase_ledger_text)

    facts = {
        "schema_version": SCHEMA_VERSION,
        "main_sha": inputs.main_sha,
        "observed_at_utc": inputs.observed_at_utc,
        "recorded_current_development_state": recorded_state,
    }
    tree_txt = "\n".join(sorted(inputs.tracked_paths)) + "\n"
    evidence = {
        "schema_version": SCHEMA_VERSION,
        "candidate": True,
        "recorded_phase_acceptance_ledger": recorded_ledger,
    }

    existing_handoff = (
        inputs.handoff_text if inputs.handoff_text is not None else INITIAL_HANDOFF_SKELETON
    )
    handoff_before = human_text_outside_block(
        existing_handoff, HANDOFF_BEGIN_MARKER, HANDOFF_END_MARKER
    )
    new_handoff = apply_bounded_block(
        existing_handoff,
        render_handoff_block(inputs.main_sha, inputs.observed_at_utc, recorded_state),
        HANDOFF_BEGIN_MARKER,
        HANDOFF_END_MARKER,
    )
    handoff_after = human_text_outside_block(new_handoff, HANDOFF_BEGIN_MARKER, HANDOFF_END_MARKER)
    if handoff_before != handoff_after:
        raise SystemExit("HANDOFF.md Human text changed across regeneration -- refusing")

    readme_before = human_text_outside_block(
        inputs.readme_text, README_BEGIN_MARKER, README_END_MARKER
    )
    new_readme = apply_bounded_block(
        inputs.readme_text,
        render_readme_block(recorded_state),
        README_BEGIN_MARKER,
        README_END_MARKER,
    )
    readme_after = human_text_outside_block(new_readme, README_BEGIN_MARKER, README_END_MARKER)
    if readme_before != readme_after:
        raise SystemExit("README.md Human text changed across regeneration -- refusing")

    outputs: dict[str, bytes] = {
        "docs/project_sources/generated/CURRENT_REPOSITORY_FACTS.json": (
            json.dumps(facts, indent=2, sort_keys=True) + "\n"
        ).encode("utf-8"),
        "docs/project_sources/generated/REPOSITORY_TREE.txt": tree_txt.encode("utf-8"),
        "docs/project_sources/generated/PHASE_EVIDENCE_INDEX.json": (
            json.dumps(evidence, indent=2, sort_keys=True) + "\n"
        ).encode("utf-8"),
        "HANDOFF.md": new_handoff.encode("utf-8"),
        "README.md": new_readme.encode("utf-8"),
    }

    # SHA256SUMS (contract section 5) covers every writable output above *plus* every
    # Human-authored docs/project_sources/*.md document -- but those source documents are
    # read-only inputs here, never written: `outputs` (the writable, allowlisted set
    # `apply_reflow` diffs and may write) must never gain a `docs/project_sources/*.md`
    # entry, only `hashed_files` (used for SHA256SUMS alone) does.
    hashed_files: dict[str, bytes] = dict(outputs)
    for path, text in inputs.source_document_texts.items():
        hashed_files[path] = text.encode("utf-8")

    outputs["SHA256SUMS"] = compute_sha256sums(hashed_files).encode("utf-8")

    escaped = set(outputs) - ALLOWLISTED_GENERATED_PATHS
    if escaped:
        raise AssertionError(f"computed output path(s) outside the allowlist: {sorted(escaped)}")
    return outputs


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp-reflow")
    tmp.write_bytes(data)
    tmp.replace(path)


def apply_reflow(root: Path, inputs: ReflowInputs) -> dict[str, Any]:
    """Compute every output, diff each against *root*'s current on-disk state, write only
    what changed (atomically, one file at a time), and return the convergence receipt.

    A computation failure inside :func:`compute_outputs` propagates before this function
    reads or writes a single byte under *root* -- see the contract document section 8.
    """

    outputs = compute_outputs(inputs)

    existing: dict[str, bytes | None] = {}
    for path in outputs:
        candidate = root / path
        existing[path] = candidate.read_bytes() if candidate.is_file() else None

    substantive_written = sorted(
        path for path, content in outputs.items() if existing[path] != content
    )
    substantive_unchanged = sorted(path for path in outputs if path not in substantive_written)

    receipt = {
        "schema_version": SCHEMA_VERSION,
        "reflowed_main_sha": inputs.main_sha,
        "observed_at_utc": inputs.observed_at_utc,
        "files_written": substantive_written,
        "files_unchanged": substantive_unchanged,
        "human_text_converged": True,
        "sha256sums_digest": hashlib.sha256(outputs["SHA256SUMS"]).hexdigest(),
        "convergence_proven": True,
    }
    receipt_bytes = (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode("utf-8")

    for path in substantive_written:
        _atomic_write(root / path, outputs[path])

    # The receipt is written only when something substantive changed in this run.
    # Otherwise two immediately-successive runs over an unchanged tree would each rewrite
    # the receipt purely to record "nothing changed" -- a non-empty write that would itself
    # break the idempotence proof this receipt exists to carry (contract section 7).
    files_written = list(substantive_written)
    files_unchanged = list(substantive_unchanged)
    if substantive_written:
        _atomic_write(root / RECEIPT_PATH, receipt_bytes)
        files_written.append(RECEIPT_PATH)
    else:
        files_unchanged.append(RECEIPT_PATH)

    return {
        "files_written": sorted(files_written),
        "files_unchanged": sorted(files_unchanged),
        "receipt": receipt,
    }


def _git_output(root: Path, *args: str) -> str:
    git = shutil.which("git")
    if git is None:
        raise SystemExit("git executable not found on PATH")
    return subprocess.run(  # noqa: S603 -- fixed Git executable resolved via shutil.which above
        [git, *args], cwd=root, check=True, capture_output=True, text=True
    ).stdout.strip()


def _gather_inputs(root: Path, main_sha: str, observed_at_utc: str) -> ReflowInputs:
    docs_dir = root / "docs" / "project_sources"
    source_document_texts: dict[str, str] = {}
    for candidate in sorted(docs_dir.glob("*.md")):
        relative = candidate.relative_to(root).as_posix()
        source_document_texts[relative] = candidate.read_text(encoding="utf-8")

    tracked_paths = tuple(
        line for line in _git_output(root, "ls-files").splitlines() if line.strip()
    )
    handoff_path = root / "HANDOFF.md"

    return ReflowInputs(
        main_sha=main_sha,
        observed_at_utc=observed_at_utc,
        current_development_state_text=(docs_dir / "03_CURRENT_DEVELOPMENT_STATE.md").read_text(
            encoding="utf-8"
        ),
        phase_ledger_text=(docs_dir / "05_PHASE_ACCEPTANCE_LEDGER.md").read_text(encoding="utf-8"),
        tracked_paths=tracked_paths,
        readme_text=(root / "README.md").read_text(encoding="utf-8"),
        handoff_text=handoff_path.read_text(encoding="utf-8") if handoff_path.is_file() else None,
        source_document_texts=source_document_texts,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--main-sha", required=True)
    parser.add_argument("--observed-at-utc", required=True)
    parser.add_argument(
        "--verify-git-head",
        action="store_true",
        help="refuse if --main-sha disagrees with `git rev-parse HEAD` of --root",
    )
    args = parser.parse_args(argv)

    if args.verify_git_head:
        verify_head_matches(args.main_sha, _git_output(args.root, "rev-parse", "HEAD"))

    inputs = _gather_inputs(args.root, args.main_sha, args.observed_at_utc)
    result = apply_reflow(args.root, inputs)
    json.dump(result, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0 if result["receipt"]["convergence_proven"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
