"""State Store protocol."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any, Protocol

FaultInjector = Callable[[str], None]

class StateStore(Protocol):
    def initialize(self, project_id: str, initial_state: Mapping[str, Any]) -> dict[str, Any]: ...
    def load_current(self, project_id: str) -> dict[str, Any]: ...
    def commit(self, project_id: str, expected_revision: int, expected_fingerprint: Mapping[str, str], next_state: Mapping[str, Any], transition: Mapping[str, Any], *, records: list[tuple[str, str, Mapping[str, Any]]] | None = None, fault: FaultInjector | None = None) -> dict[str, Any]: ...
    def recover(self, project_id: str) -> dict[str, Any]: ...
    def reconstruct(self, project_id: str) -> dict[str, Any]: ...
    def resolve_record(self, project_id: str, kind: str, record_id: str) -> dict[str, Any] | None: ...
